name: check-coding-style-and-push-to-compile-program
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
  pull_request:
    branches-ignore:
      - ga-ignore-*
env:
   MIRROR_URL: git@github.com:EpitechPromo2028/B-DOP-200-COT-2-2-chocolatine-romaric.dega.git
   EXECUTABLES: binary
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: check actions in the repository
        uses: actions/checkout@v4
      - name: execute coding-style
        run: check.sh $(pwd) $(pwd)
      - name: display coding-style
        if: failure()
        run: cat coding-style-reports.log
  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_coding_style
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: check actions in the repository
        uses: actions/checkout@v4
      - name: compile the program
        run: make
      - name: clean up and compile the program
        run: make clean
      - name: check executables
        run: |
          if [ -f $EXECUTABLES]; then
            exit 1
          fi
  run_tests:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: check actions in the repository
        uses: actions/checkout@v4
      - name: compile tests
        run: make tests_run
  push_to_mirror:
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  push_to_mirror:
    runs-on: ubuntu-latest
    needs: run_tests
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v0.3.0
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
